### ISSUE TITLE
document is not defined

### ISSUE THREAD

**Issue by anoora17** [ChiefORZ/popupS#2]
I tried to use  your model however after installin the npm package and try your sample code i keep getting this error.

var el = document.createElement("fakeelement");
                          ^
 
ReferenceError: document is not defined

**Comment by dimplesharma21** [comment]
I am facing the same problem.

**Comment by gabrielerzinger** [comment]
Same problem here =/

**Comment by FuKwon** [comment]
Any news on this matter ?

**Comment by gabrielerzinger** [comment]
No, i could'nt be able to fix that, so i just switch over to SWAL js

**Comment by dileephell** [comment]
I too got the same issue 👎

**Comment by sreyas** [comment]
Same problem happened for me also.

**Comment by shreyas1701** [comment]
I am too getting a similar issue. Kindly find the attached screenshot. TIA
![image](https://user-images.githubusercontent.com/22567445/55616471-e65ee880-575f-11e9-8742-86ea3c63d07b.png)

**Comment by ChiefORZ** [comment]
this library was built for a small project, which is not in development nor in use any more.
i recommend using another popup library like [sweetalert](https://github.com/t4t5/sweetalert).
