### ISSUE TITLE
onCancel event.

### ISSUE THREAD

**Issue by GrumpyCrouton** [ChiefORZ/popupS#6]
There should be an event for onCancel so that you don't have to use onClose. When you click off of the popop box, it throws an onClose event, meaning that if you have 2 different options in a popup, like this:

```
popupS.confirm({
    content:     '<b>Do you like what you see?</b>',
    labelOk:     'Yes',
    labelCancel: 'No',
    onSubmit: function() {
        console.log(':)');
    },
    onClose: function() {
        console.log(':(');
    }
});
```

clicking off of the popup will make `console.log(':(');` run, which may not be proper behavior for any app.

For example, in the app I am working on, I have several nested popups.

```
popupS.confirm({
		content:     '<span style="color:black;">We need some more information.<br>Would you like to input a UPC or a Model?</span>',
		labelOk:     'UPC',
		labelCancel: 'Model',
		onSubmit: function() {
			popupS.prompt({
				content: 'Please enter a UPC',
				onSubmit: function(val) {
					popupS.alert({
						content: 'Hi, ' + val + '!'
					});
				},
				onClose: function() {
					insertModel();
				}
			});
		},
		onClose: function() {
			popupS.prompt({
				content: 'Please enter a Model',
				onSubmit: function(val) {
					popupS.alert({
						content: 'Hi, ' + val + '!'
					});
				},
				onClose: function() {
					insertModel();
				}
			});
		}
	});
```

When the user gets to this page and a popup happens, the user has 2 options "UPC" and "Model". Each respective button will launch a new popup with an input box. The problem is, if the user accidentally clicks off of the popup it will default to "Please enter a Model". Easy enough, just put a cancel button which restarts the the popup right? That's what I've done. As you can se in onClose in the nested popups, I recall the function that started the popup anyways. This works okay for a cancel button, but there is a deeper problem. Say the user selects "UPC" in the first dialogue, then they accidentally click off of the pop. For some reason, this will switch the popup to "Please enter a Model" (Which is unexpected). It also seems that occasianlly if this happens, it will lock up the buttons on the "Please enter a Model" page, where neither button works, and I can't force close the app with alt+F4, I have to close it by right clicking the executable in the taskbar.

**Comment by GrumpyCrouton** [comment]
Also, why does pressing enter when on a `prompt()` reload the page/call onClose?

**Comment by ChiefORZ** [comment]
this library was built for a small project, which is not in development nor in use any more.
i recommend using another popup library like [sweetalert](https://github.com/t4t5/sweetalert).
