### ISSUE TITLE
Error : document is not defined 

### ISSUE THREAD

**Issue by mehrdadmms** [ChiefORZ/popupS#7]
i wanted to show an alert but i faced this error .

F:\DEV\nodeJS - expressJS\instagram\test2>node app.js
F:\DEV\nodeJS - expressJS\instagram\test2\node_modules\popups\dist\popupS.js:29
        appendLocation: (document.body || document.documentElement),
                         ^

ReferenceError:

 document is not defined
    at F:\DEV\nodeJS - expressJS\instagram\test2\node_modules\popups\dist\popupS.js:29:26
    at isOpen (F:\DEV\nodeJS - expressJS\instagram\test2\node_modules\popups\dist\popupS.js:6:26)
    at Object.<anonymous> (F:\DEV\nodeJS - expressJS\instagram\test2\node_modules\popups\dist\popupS.js:11:2)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)

what shoul i do ?

**Comment by TimGab** [comment]
I'm facing the same issue. Please help.

**Comment by aboumekh** [comment]
Me too I am having the same issue

**Comment by jkelly-cas** [comment]
Very generally "document not defined" errors mean just that; there is no document DOM object to latch onto. I suspect you're trying to import the popups class outside of the final HTML document.

You should also get in the habit of posting your code so the maintainer has a chance to help debug the issue, and has a better idea of how you're trying to use his code.

**Comment by akratichatur** [comment]
I am facing the same error. can anyone help me in this?

**Comment by ashish-patidar-rau** [comment]
I am facing the same error. can help me?

**Comment by harshini66** [comment]
I am facing the same issue while compiling document is not defined.
 at C:\Users\nodejs\node_modules\popups\dist\popupS.js:29:26
    at C:\Users\nodejs\node_modules\popups\dist\popupS.js:6:26
    at Object.<anonymous> (C:\Users\nodejs\node_modules\popups\dist\popupS.js:11:2)

**Comment by shreyas1701** [comment]
I am too getting a similar issue. Kindly find the attached screenshot. TIA
![image](https://user-images.githubusercontent.com/22567445/55616471-e65ee880-575f-11e9-8742-86ea3c63d07b.png)

**Comment by ChiefORZ** [comment]
this library was built for a small project, which is not in development nor in use any more.
i recommend using another popup library like [sweetalert](https://github.com/t4t5/sweetalert).
