### ISSUE TITLE
Also, why does pressing enter when on a `prompt()` reload the page/call onClose?

### ISSUE THREAD

**Issue by pncolin** [ChiefORZ/popupS#8]
_Originally posted by @GrumpyCrouton in https://github.com/ChiefORZ/popupS/issues/6#issuecomment-386720205_

I am experiencing this as well.
I'm using popupS in an Electron-based SPA app, and hitting Enter on a prompt does a full reload, taking my users away from whatever they were doing.

Is there a way to disable this behavior?

**Comment by ChiefORZ** [comment]
this library was built for a small project, which is not in development nor in use any more.
i recommend using another popup library like [sweetalert](https://github.com/t4t5/sweetalert).
